// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMeSUkfFg4htwlKxK8Q523_a92SkYzj0E',
    appId: '1:375614378782:web:359d6dc164fcdbff276f0f',
    messagingSenderId: '375614378782',
    projectId: 'course-courze',
    authDomain: 'course-courze.firebaseapp.com',
    storageBucket: 'course-courze.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALPrubvUbjSoyGV_BII3NZRCOQMTTTYAA',
    appId: '1:375614378782:android:e2322fae1625ccca276f0f',
    messagingSenderId: '375614378782',
    projectId: 'course-courze',
    storageBucket: 'course-courze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3n--CaCamAbDhGqVpQxhSMWGqRW-EIy8',
    appId: '1:375614378782:ios:314030c8ec6fc981276f0f',
    messagingSenderId: '375614378782',
    projectId: 'course-courze',
    storageBucket: 'course-courze.appspot.com',
    iosBundleId: 'com.example.flutterFeRpl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3n--CaCamAbDhGqVpQxhSMWGqRW-EIy8',
    appId: '1:375614378782:ios:345947db1227fc59276f0f',
    messagingSenderId: '375614378782',
    projectId: 'course-courze',
    storageBucket: 'course-courze.appspot.com',
    iosBundleId: 'com.example.flutterFeRpl.RunnerTests',
  );
}
